version: "3.7"

services:
  db-passengers:
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: passengers
  db-drivers:
    image: postgres:latest
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: drivers
  db-rides:
    image: postgres:latest
    ports:
      - "5446:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rides