spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**,/api/v1/promos/**
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5