spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: taxi-realm
            client-secret: ${REALM-SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid
        provider:
          keycloak:
            token-uri: http://localhost:8181/realms/taxi-realm/protocol/openid-connect/token
            authorization-uri: http://localhost:8181/realms/taxi-realm/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: http://localhost:8181/realms/taxi-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8181/realms/taxi-realm/protocol/openid-connect/certs
            user-info-authentication-method: header
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8181/realms/taxi-realm
          jwk-set-uri: http://localhost:8181/realms/taxi-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**,/api/v1/promos/**
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**
      discovery:
        locator:
          enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5