server:
  port: 8084
stripe:
  keys:
    pk: ${STRIPE_API_PUBLIC_KEY}
    sk: ${STRIPE_API_SECRET_KEY}
spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-payments:5447/payments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
feign:
  client:
    config:
      ride:
        name: ride-service
        path: /api/v1/rides
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5