server:
  port: 8082
spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5444/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
