server:
  port: 8082
spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-drivers:5445/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/taxi-realm
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
jwt:
  auth:
    converter:
      resource-id: taxi-realm
      principal-attribute: sub