server:
  port: 8080
spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-drivers:5445/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
management:
  endpoint.health.show-details: "ALWAYS"
  endpoints.web.exposure.include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 0.5
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
