server:
  port: 8083
spring:
  application:
    name: ride-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5446/rides}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
feign:
  client:
    config:
      driver:
        name: driver-service
        url: http://localhost:8082
        path: /api/v1/drivers
      passenger:
        name: passenger-service
        url: http://localhost:8081
        path: /api/v1/passengers