server:
  port: 8081
spring:
  application:
    name: passenger-service
  datasource:
    url: jdbc:postgresql://localhost:5432/passengers
    username: postgres
    password: ${DB_PASSWORD}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
