server:
  port: 8081
spring:
  application:
    name: passenger-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-passengers:5444/passengers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    dbcp2:
      driver: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
feign:
  client:
    config:
      payment:
        name: payment-service
        path: /api/v1/payments
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5