[email]
invalid.empty = "Email is empty"
invalid.pattern = "Invalid email pattern"

[phone]
invalid.empty = "Phone is empty"
invalid.pattern = "Invalid phone pattern"

[surname]
invalid.empty = "Surname is empty"

[name]
invalid.empty = "Name is empty"